POST https://projeto-node-y546.onrender.com/videos
Content-Type: application/json

{
    "title": "video 01",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://projeto-node-y546.onrender.com/videos

###

PUT https://projeto-node-y546.onrender.com/videos/e42ca60a-58f4-4380-b0a7-d0e64edfc1bf
Content-Type: application/json

{
    "title": "video 02",
    "description": "Esse é o segundo video",
    "duration": 180
}

###

DELETE https://projeto-node-y546.onrender.com/videos/f7012b13-8352-4d00-9073-84793594bf68